export default [
  {
    path: '/',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
    hideInMenu: true,
  },
  {
    path: '/playground',
    name: 'playground',
    icon: 'appstore',
    component: './Playground',
  },
  {
    key: 'utility',
    name: 'utility',
    icon: 'tool',
    routes: [
      { path: '/utility/qr', name: 'qr', icon: 'qrcode', component: './QR' },
      {
        path: '/utility/video-analyzer',
        name: 'video-analyzer',
        icon: 'playCircle',
        component: './VideoAnalyzer',
      },
      { path: '/utility/epoch', name: 'epoch', icon: 'clockCircle', component: './Epoch' },
      { path: '/utility/regex', name: 'regex', icon: 'code', component: './Regex' },
      { path: '/utility/uuid', name: 'uuid', icon: 'barcode', component: './UUID' },
      { path: '/utility/password', name: 'password', icon: 'key', component: './Password' },
      { path: '/utility/jwt', name: 'jwt', icon: 'idcard', component: './JWT' },
      { path: '/utility/hex', name: 'hex', icon: 'highlight', component: './HexConverter' },
      { path: '/utility/aes', name: 'aes', icon: 'lock', component: './AesConverter' },
      {
        path: '/utility/colorpicker',
        name: 'colorpicker',
        icon: 'bgColors',
        component: './ColorPicker',
      },
      {
        path: '/utility/stress-test',
        name: 'stress-test',
        icon: 'thunderbolt',
        component: './StressTest',
      },
      {
        path: '/utility/system-info',
        name: 'system-info',
        icon: 'laptop',
        component: './SystemInfo',
      },
      {
        path: '/utility/device-test',
        name: 'device-test',
        icon: 'desktop',
        component: './DeviceTest',
        routes: [
          { path: '/utility/device-test', redirect: '/utility/device-test/keyboard' },
          { path: '/utility/device-test/keyboard', component: './DeviceTest' },
          { path: '/utility/device-test/camera', component: './DeviceTest' },
          { path: '/utility/device-test/microphone', component: './DeviceTest' },
          { path: '/utility/device-test/headphone', component: './DeviceTest' },
          { path: '/utility/device-test/gamepad', component: './DeviceTest' },
          { path: '/utility/device-test/mouse', component: './DeviceTest' },
        ],
      },
    ],
  },
  {
    key: 'visual-tools',
    name: 'visual-tools',
    icon: 'picture',
    routes: [
      {
        path: '/visual-tools/image-to-text',
        name: 'image-to-text',
        icon: 'fileSearch',
        component: './ImageToText',
      },
      {
        path: '/visual-tools/svg-viewer',
        name: 'svg-viewer',
        icon: 'fileImage',
        component: './SVGViewer',
      },
      // {
      //   path: '/visual-tools/pics-editor',
      //   name: 'pics-editor',
      //   icon: 'fileImage',
      //   component: './PicsEditor',
      // },
      {
        path: '/visual-tools/photo-editor',
        name: 'photo-editor',
        icon: 'fileImage',
        component: './PhotoEditor',
      },
      {
        path: '/visual-tools/vector-editor',
        name: 'vector-editor',
        icon: 'edit',
        component: './VectorEditor',
      },
      { path: '/visual-tools/base64', name: 'base64', icon: 'fileText', component: './Base64' },
      {
        path: '/visual-tools/text-art',
        name: 'text-art',
        icon: 'fontColors',
        component: './TextArt',
      },
    ],
  },
  {
    key: 'editor',
    name: 'editor',
    icon: 'edit',
    routes: [
      {
        path: '/editor/readme-editor',
        name: 'readme-editor',
        icon: 'fileMarkdown',
        component: './ReadmeEditor',
      },
      {
        path: '/editor/json-formatter',
        name: 'json-formatter',
        icon: 'fileText',
        component: './JsonFormatter',
      },
      {
        path: '/editor/html-editor',
        name: 'html-editor',
        icon: 'file',
        component: './HtmlEditor',
      },
      {
        path: '/editor/mermaid-editor',
        name: 'mermaid-editor',
        icon: 'apartmentOutlined',
        component: './MermaidEditor',
      },
    ],
  },
  {
    key: 'randomizer',
    name: 'randomizer',
    icon: '🎲',
    routes: [
      {
        path: '/randomizer/wheel-of-names',
        name: 'wheel-of-names',
        icon: 'sync',
        component: './WheelOfNames',
      },
      {
        path: '/randomizer/random',
        name: 'random',
        icon: 'questionCircle',
        component: './Random',
      },
    ],
  },
  {
    key: 'game',
    name: 'game',
    icon: '🎮',
    routes: [
      {
        path: '/game/tic-tac-toe',
        name: 'tic-tac-toe',
        icon: '❌',
        component: './TicTacToe',
      },
      {
        path: '/game/snake-xenzia',
        name: 'snake-xenzia',
        icon: '🐍',
        component: './SnakeXenzia',
      },
      {
        path: '/game/minesweeper',
        name: 'minesweeper',
        icon: '💣',
        component: './Minesweeper',
      },
      {
        path: '/game/sudoku',
        name: 'sudoku',
        icon: '9️⃣',
        component: './Sudoku',
      },
      {
        path: '/game/chess',
        name: 'chess',
        icon: '♟️',
        component: './Chess',
      },
    ],
  },
  {
    key: 'docs',
    name: 'docs',
    icon: 'fileText',
    routes: [
      { path: '/docs/commands', name: 'commands', icon: 'fileText', component: './Commands' },
      { path: '/docs/emojis', name: 'emojis', icon: 'smile', component: './Emojis' },
      {
        path: '/docs/google-drive',
        name: 'google-drive',
        icon: 'cloud',
        component: './GoogleDrive',
      },
      {
        path: '/docs/google-photos',
        name: 'google-photos',
        icon: 'picture',
        component: './GooglePhotos',
      },
    ],
  },

  {
    path: '/webflow-scroll',
    name: 'Webflow Scroll',
    icon: 'verticalAlignMiddle',
    component: './WebflowScroll',
    hideInMenu: true,
  },
  { path: '*', component: './404', icon: 'frown' },
];
